//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8762
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace NewConsolidado.Vistas.Reportes.ESF {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtsEstadoSituacion")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtsEstadoSituacion : global::System.Data.DataSet {
        
        private tblEstadoSituacionDataTable tabletblEstadoSituacion;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtsEstadoSituacion() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dtsEstadoSituacion(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblEstadoSituacion"] != null)) {
                    base.Tables.Add(new tblEstadoSituacionDataTable(ds.Tables["tblEstadoSituacion"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblEstadoSituacionDataTable tblEstadoSituacion {
            get {
                return this.tabletblEstadoSituacion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dtsEstadoSituacion cln = ((dtsEstadoSituacion)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tblEstadoSituacion"] != null)) {
                    base.Tables.Add(new tblEstadoSituacionDataTable(ds.Tables["tblEstadoSituacion"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabletblEstadoSituacion = ((tblEstadoSituacionDataTable)(base.Tables["tblEstadoSituacion"]));
            if ((initTable == true)) {
                if ((this.tabletblEstadoSituacion != null)) {
                    this.tabletblEstadoSituacion.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dtsEstadoSituacion";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtsEstadoSituacion.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletblEstadoSituacion = new tblEstadoSituacionDataTable();
            base.Tables.Add(this.tabletblEstadoSituacion);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializetblEstadoSituacion() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtsEstadoSituacion ds = new dtsEstadoSituacion();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void tblEstadoSituacionRowChangeEventHandler(object sender, tblEstadoSituacionRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tblEstadoSituacionDataTable : global::System.Data.TypedTableBase<tblEstadoSituacionRow> {
            
            private global::System.Data.DataColumn columnidConsolidado;
            
            private global::System.Data.DataColumn columnDescripcionConsolidado;
            
            private global::System.Data.DataColumn columnidCompania;
            
            private global::System.Data.DataColumn columnDescripcionCompania;
            
            private global::System.Data.DataColumn columnidGrupo;
            
            private global::System.Data.DataColumn columnDescripcionGrupo;
            
            private global::System.Data.DataColumn columnidConcepto;
            
            private global::System.Data.DataColumn columnDescripcionConcepto;
            
            private global::System.Data.DataColumn columnidCuenta;
            
            private global::System.Data.DataColumn columnDescripcionCuenta;
            
            private global::System.Data.DataColumn columnidPeriodo;
            
            private global::System.Data.DataColumn columnValor;
            
            private global::System.Data.DataColumn columnFlagImprime;
            
            private global::System.Data.DataColumn columnFlagPatrimonio;
            
            private global::System.Data.DataColumn columnDescripcionFlag;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionDataTable() {
                this.TableName = "tblEstadoSituacion";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoSituacionDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected tblEstadoSituacionDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idConsolidadoColumn {
                get {
                    return this.columnidConsolidado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConsolidadoColumn {
                get {
                    return this.columnDescripcionConsolidado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idCompaniaColumn {
                get {
                    return this.columnidCompania;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionCompaniaColumn {
                get {
                    return this.columnDescripcionCompania;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idGrupoColumn {
                get {
                    return this.columnidGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionGrupoColumn {
                get {
                    return this.columnDescripcionGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idConceptoColumn {
                get {
                    return this.columnidConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConceptoColumn {
                get {
                    return this.columnDescripcionConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idCuentaColumn {
                get {
                    return this.columnidCuenta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionCuentaColumn {
                get {
                    return this.columnDescripcionCuenta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idPeriodoColumn {
                get {
                    return this.columnidPeriodo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ValorColumn {
                get {
                    return this.columnValor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FlagImprimeColumn {
                get {
                    return this.columnFlagImprime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FlagPatrimonioColumn {
                get {
                    return this.columnFlagPatrimonio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionFlagColumn {
                get {
                    return this.columnDescripcionFlag;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionRow this[int index] {
                get {
                    return ((tblEstadoSituacionRow)(this.Rows[index]));
                }
            }
            
            public event tblEstadoSituacionRowChangeEventHandler tblEstadoSituacionRowChanging;
            
            public event tblEstadoSituacionRowChangeEventHandler tblEstadoSituacionRowChanged;
            
            public event tblEstadoSituacionRowChangeEventHandler tblEstadoSituacionRowDeleting;
            
            public event tblEstadoSituacionRowChangeEventHandler tblEstadoSituacionRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddtblEstadoSituacionRow(tblEstadoSituacionRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionRow AddtblEstadoSituacionRow(int idConsolidado, string DescripcionConsolidado, string idCompania, string DescripcionCompania, string idGrupo, string DescripcionGrupo, string idConcepto, string DescripcionConcepto, string idCuenta, string DescripcionCuenta, string idPeriodo, decimal Valor, int FlagImprime, string FlagPatrimonio, string DescripcionFlag) {
                tblEstadoSituacionRow rowtblEstadoSituacionRow = ((tblEstadoSituacionRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        idConsolidado,
                        DescripcionConsolidado,
                        idCompania,
                        DescripcionCompania,
                        idGrupo,
                        DescripcionGrupo,
                        idConcepto,
                        DescripcionConcepto,
                        idCuenta,
                        DescripcionCuenta,
                        idPeriodo,
                        Valor,
                        FlagImprime,
                        FlagPatrimonio,
                        DescripcionFlag};
                rowtblEstadoSituacionRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtblEstadoSituacionRow);
                return rowtblEstadoSituacionRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                tblEstadoSituacionDataTable cln = ((tblEstadoSituacionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tblEstadoSituacionDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnidConsolidado = base.Columns["idConsolidado"];
                this.columnDescripcionConsolidado = base.Columns["DescripcionConsolidado"];
                this.columnidCompania = base.Columns["idCompania"];
                this.columnDescripcionCompania = base.Columns["DescripcionCompania"];
                this.columnidGrupo = base.Columns["idGrupo"];
                this.columnDescripcionGrupo = base.Columns["DescripcionGrupo"];
                this.columnidConcepto = base.Columns["idConcepto"];
                this.columnDescripcionConcepto = base.Columns["DescripcionConcepto"];
                this.columnidCuenta = base.Columns["idCuenta"];
                this.columnDescripcionCuenta = base.Columns["DescripcionCuenta"];
                this.columnidPeriodo = base.Columns["idPeriodo"];
                this.columnValor = base.Columns["Valor"];
                this.columnFlagImprime = base.Columns["FlagImprime"];
                this.columnFlagPatrimonio = base.Columns["FlagPatrimonio"];
                this.columnDescripcionFlag = base.Columns["DescripcionFlag"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnidConsolidado = new global::System.Data.DataColumn("idConsolidado", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidConsolidado);
                this.columnDescripcionConsolidado = new global::System.Data.DataColumn("DescripcionConsolidado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConsolidado);
                this.columnidCompania = new global::System.Data.DataColumn("idCompania", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidCompania);
                this.columnDescripcionCompania = new global::System.Data.DataColumn("DescripcionCompania", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionCompania);
                this.columnidGrupo = new global::System.Data.DataColumn("idGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidGrupo);
                this.columnDescripcionGrupo = new global::System.Data.DataColumn("DescripcionGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionGrupo);
                this.columnidConcepto = new global::System.Data.DataColumn("idConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidConcepto);
                this.columnDescripcionConcepto = new global::System.Data.DataColumn("DescripcionConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConcepto);
                this.columnidCuenta = new global::System.Data.DataColumn("idCuenta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidCuenta);
                this.columnDescripcionCuenta = new global::System.Data.DataColumn("DescripcionCuenta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionCuenta);
                this.columnidPeriodo = new global::System.Data.DataColumn("idPeriodo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidPeriodo);
                this.columnValor = new global::System.Data.DataColumn("Valor", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnValor);
                this.columnFlagImprime = new global::System.Data.DataColumn("FlagImprime", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFlagImprime);
                this.columnFlagPatrimonio = new global::System.Data.DataColumn("FlagPatrimonio", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFlagPatrimonio);
                this.columnDescripcionFlag = new global::System.Data.DataColumn("DescripcionFlag", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionFlag);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionRow NewtblEstadoSituacionRow() {
                return ((tblEstadoSituacionRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tblEstadoSituacionRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(tblEstadoSituacionRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblEstadoSituacionRowChanged != null)) {
                    this.tblEstadoSituacionRowChanged(this, new tblEstadoSituacionRowChangeEvent(((tblEstadoSituacionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblEstadoSituacionRowChanging != null)) {
                    this.tblEstadoSituacionRowChanging(this, new tblEstadoSituacionRowChangeEvent(((tblEstadoSituacionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblEstadoSituacionRowDeleted != null)) {
                    this.tblEstadoSituacionRowDeleted(this, new tblEstadoSituacionRowChangeEvent(((tblEstadoSituacionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblEstadoSituacionRowDeleting != null)) {
                    this.tblEstadoSituacionRowDeleting(this, new tblEstadoSituacionRowChangeEvent(((tblEstadoSituacionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovetblEstadoSituacionRow(tblEstadoSituacionRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtsEstadoSituacion ds = new dtsEstadoSituacion();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tblEstadoSituacionDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class tblEstadoSituacionRow : global::System.Data.DataRow {
            
            private tblEstadoSituacionDataTable tabletblEstadoSituacion;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoSituacionRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblEstadoSituacion = ((tblEstadoSituacionDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int idConsolidado {
                get {
                    try {
                        return ((int)(this[this.tabletblEstadoSituacion.idConsolidadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idConsolidado\' de la tabla \'tblEstadoSituacion\' es DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.idConsolidadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConsolidado {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.DescripcionConsolidadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConsolidado\' de la tabla \'tblEstadoSituacion\' " +
                                "es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.DescripcionConsolidadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idCompania {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.idCompaniaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idCompania\' de la tabla \'tblEstadoSituacion\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.idCompaniaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionCompania {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.DescripcionCompaniaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionCompania\' de la tabla \'tblEstadoSituacion\' es " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.DescripcionCompaniaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.idGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idGrupo\' de la tabla \'tblEstadoSituacion\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.idGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.DescripcionGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionGrupo\' de la tabla \'tblEstadoSituacion\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.DescripcionGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.idConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idConcepto\' de la tabla \'tblEstadoSituacion\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.idConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.DescripcionConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConcepto\' de la tabla \'tblEstadoSituacion\' es " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.DescripcionConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idCuenta {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.idCuentaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idCuenta\' de la tabla \'tblEstadoSituacion\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.idCuentaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionCuenta {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.DescripcionCuentaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionCuenta\' de la tabla \'tblEstadoSituacion\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.DescripcionCuentaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idPeriodo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.idPeriodoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idPeriodo\' de la tabla \'tblEstadoSituacion\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.idPeriodoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Valor {
                get {
                    try {
                        return ((decimal)(this[this.tabletblEstadoSituacion.ValorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'Valor\' de la tabla \'tblEstadoSituacion\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.ValorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int FlagImprime {
                get {
                    try {
                        return ((int)(this[this.tabletblEstadoSituacion.FlagImprimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'FlagImprime\' de la tabla \'tblEstadoSituacion\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.FlagImprimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FlagPatrimonio {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.FlagPatrimonioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'FlagPatrimonio\' de la tabla \'tblEstadoSituacion\' es DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.FlagPatrimonioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionFlag {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacion.DescripcionFlagColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionFlag\' de la tabla \'tblEstadoSituacion\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacion.DescripcionFlagColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidConsolidadoNull() {
                return this.IsNull(this.tabletblEstadoSituacion.idConsolidadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidConsolidadoNull() {
                this[this.tabletblEstadoSituacion.idConsolidadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConsolidadoNull() {
                return this.IsNull(this.tabletblEstadoSituacion.DescripcionConsolidadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConsolidadoNull() {
                this[this.tabletblEstadoSituacion.DescripcionConsolidadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidCompaniaNull() {
                return this.IsNull(this.tabletblEstadoSituacion.idCompaniaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidCompaniaNull() {
                this[this.tabletblEstadoSituacion.idCompaniaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionCompaniaNull() {
                return this.IsNull(this.tabletblEstadoSituacion.DescripcionCompaniaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionCompaniaNull() {
                this[this.tabletblEstadoSituacion.DescripcionCompaniaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidGrupoNull() {
                return this.IsNull(this.tabletblEstadoSituacion.idGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidGrupoNull() {
                this[this.tabletblEstadoSituacion.idGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionGrupoNull() {
                return this.IsNull(this.tabletblEstadoSituacion.DescripcionGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionGrupoNull() {
                this[this.tabletblEstadoSituacion.DescripcionGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidConceptoNull() {
                return this.IsNull(this.tabletblEstadoSituacion.idConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidConceptoNull() {
                this[this.tabletblEstadoSituacion.idConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConceptoNull() {
                return this.IsNull(this.tabletblEstadoSituacion.DescripcionConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConceptoNull() {
                this[this.tabletblEstadoSituacion.DescripcionConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidCuentaNull() {
                return this.IsNull(this.tabletblEstadoSituacion.idCuentaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidCuentaNull() {
                this[this.tabletblEstadoSituacion.idCuentaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionCuentaNull() {
                return this.IsNull(this.tabletblEstadoSituacion.DescripcionCuentaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionCuentaNull() {
                this[this.tabletblEstadoSituacion.DescripcionCuentaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidPeriodoNull() {
                return this.IsNull(this.tabletblEstadoSituacion.idPeriodoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidPeriodoNull() {
                this[this.tabletblEstadoSituacion.idPeriodoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsValorNull() {
                return this.IsNull(this.tabletblEstadoSituacion.ValorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetValorNull() {
                this[this.tabletblEstadoSituacion.ValorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFlagImprimeNull() {
                return this.IsNull(this.tabletblEstadoSituacion.FlagImprimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFlagImprimeNull() {
                this[this.tabletblEstadoSituacion.FlagImprimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFlagPatrimonioNull() {
                return this.IsNull(this.tabletblEstadoSituacion.FlagPatrimonioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFlagPatrimonioNull() {
                this[this.tabletblEstadoSituacion.FlagPatrimonioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionFlagNull() {
                return this.IsNull(this.tabletblEstadoSituacion.DescripcionFlagColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionFlagNull() {
                this[this.tabletblEstadoSituacion.DescripcionFlagColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class tblEstadoSituacionRowChangeEvent : global::System.EventArgs {
            
            private tblEstadoSituacionRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionRowChangeEvent(tblEstadoSituacionRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591