//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8762
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace NewConsolidado.Vistas.Reportes.ERF {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtsEstadoResultado")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtsEstadoResultado : global::System.Data.DataSet {
        
        private tblEstadoResultadoDataTable tabletblEstadoResultado;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtsEstadoResultado() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dtsEstadoResultado(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblEstadoResultado"] != null)) {
                    base.Tables.Add(new tblEstadoResultadoDataTable(ds.Tables["tblEstadoResultado"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblEstadoResultadoDataTable tblEstadoResultado {
            get {
                return this.tabletblEstadoResultado;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dtsEstadoResultado cln = ((dtsEstadoResultado)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tblEstadoResultado"] != null)) {
                    base.Tables.Add(new tblEstadoResultadoDataTable(ds.Tables["tblEstadoResultado"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabletblEstadoResultado = ((tblEstadoResultadoDataTable)(base.Tables["tblEstadoResultado"]));
            if ((initTable == true)) {
                if ((this.tabletblEstadoResultado != null)) {
                    this.tabletblEstadoResultado.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dtsEstadoResultado";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtsEstadoResultado.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletblEstadoResultado = new tblEstadoResultadoDataTable();
            base.Tables.Add(this.tabletblEstadoResultado);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializetblEstadoResultado() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtsEstadoResultado ds = new dtsEstadoResultado();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void tblEstadoResultadoRowChangeEventHandler(object sender, tblEstadoResultadoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tblEstadoResultadoDataTable : global::System.Data.TypedTableBase<tblEstadoResultadoRow> {
            
            private global::System.Data.DataColumn columnidConsolidado;
            
            private global::System.Data.DataColumn columnDescripcionConsolidado;
            
            private global::System.Data.DataColumn columnidCompania;
            
            private global::System.Data.DataColumn columnDescripcionCompania;
            
            private global::System.Data.DataColumn columnidGrupo;
            
            private global::System.Data.DataColumn columnDescripcionGrupo;
            
            private global::System.Data.DataColumn columnidConcepto;
            
            private global::System.Data.DataColumn columnDescripcionConcepto;
            
            private global::System.Data.DataColumn columnidCuenta;
            
            private global::System.Data.DataColumn columnDescripcionCuenta;
            
            private global::System.Data.DataColumn columnidPeriodo;
            
            private global::System.Data.DataColumn columnValor;
            
            private global::System.Data.DataColumn columnFlagImprime;
            
            private global::System.Data.DataColumn columnTipo;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoDataTable() {
                this.TableName = "tblEstadoResultado";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoResultadoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected tblEstadoResultadoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idConsolidadoColumn {
                get {
                    return this.columnidConsolidado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConsolidadoColumn {
                get {
                    return this.columnDescripcionConsolidado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idCompaniaColumn {
                get {
                    return this.columnidCompania;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionCompaniaColumn {
                get {
                    return this.columnDescripcionCompania;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idGrupoColumn {
                get {
                    return this.columnidGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionGrupoColumn {
                get {
                    return this.columnDescripcionGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idConceptoColumn {
                get {
                    return this.columnidConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConceptoColumn {
                get {
                    return this.columnDescripcionConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idCuentaColumn {
                get {
                    return this.columnidCuenta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionCuentaColumn {
                get {
                    return this.columnDescripcionCuenta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idPeriodoColumn {
                get {
                    return this.columnidPeriodo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ValorColumn {
                get {
                    return this.columnValor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FlagImprimeColumn {
                get {
                    return this.columnFlagImprime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipoColumn {
                get {
                    return this.columnTipo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoRow this[int index] {
                get {
                    return ((tblEstadoResultadoRow)(this.Rows[index]));
                }
            }
            
            public event tblEstadoResultadoRowChangeEventHandler tblEstadoResultadoRowChanging;
            
            public event tblEstadoResultadoRowChangeEventHandler tblEstadoResultadoRowChanged;
            
            public event tblEstadoResultadoRowChangeEventHandler tblEstadoResultadoRowDeleting;
            
            public event tblEstadoResultadoRowChangeEventHandler tblEstadoResultadoRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddtblEstadoResultadoRow(tblEstadoResultadoRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoRow AddtblEstadoResultadoRow(int idConsolidado, string DescripcionConsolidado, string idCompania, string DescripcionCompania, string idGrupo, string DescripcionGrupo, string idConcepto, string DescripcionConcepto, string idCuenta, string DescripcionCuenta, string idPeriodo, decimal Valor, int FlagImprime, string Tipo) {
                tblEstadoResultadoRow rowtblEstadoResultadoRow = ((tblEstadoResultadoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        idConsolidado,
                        DescripcionConsolidado,
                        idCompania,
                        DescripcionCompania,
                        idGrupo,
                        DescripcionGrupo,
                        idConcepto,
                        DescripcionConcepto,
                        idCuenta,
                        DescripcionCuenta,
                        idPeriodo,
                        Valor,
                        FlagImprime,
                        Tipo};
                rowtblEstadoResultadoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtblEstadoResultadoRow);
                return rowtblEstadoResultadoRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                tblEstadoResultadoDataTable cln = ((tblEstadoResultadoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tblEstadoResultadoDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnidConsolidado = base.Columns["idConsolidado"];
                this.columnDescripcionConsolidado = base.Columns["DescripcionConsolidado"];
                this.columnidCompania = base.Columns["idCompania"];
                this.columnDescripcionCompania = base.Columns["DescripcionCompania"];
                this.columnidGrupo = base.Columns["idGrupo"];
                this.columnDescripcionGrupo = base.Columns["DescripcionGrupo"];
                this.columnidConcepto = base.Columns["idConcepto"];
                this.columnDescripcionConcepto = base.Columns["DescripcionConcepto"];
                this.columnidCuenta = base.Columns["idCuenta"];
                this.columnDescripcionCuenta = base.Columns["DescripcionCuenta"];
                this.columnidPeriodo = base.Columns["idPeriodo"];
                this.columnValor = base.Columns["Valor"];
                this.columnFlagImprime = base.Columns["FlagImprime"];
                this.columnTipo = base.Columns["Tipo"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnidConsolidado = new global::System.Data.DataColumn("idConsolidado", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidConsolidado);
                this.columnDescripcionConsolidado = new global::System.Data.DataColumn("DescripcionConsolidado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConsolidado);
                this.columnidCompania = new global::System.Data.DataColumn("idCompania", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidCompania);
                this.columnDescripcionCompania = new global::System.Data.DataColumn("DescripcionCompania", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionCompania);
                this.columnidGrupo = new global::System.Data.DataColumn("idGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidGrupo);
                this.columnDescripcionGrupo = new global::System.Data.DataColumn("DescripcionGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionGrupo);
                this.columnidConcepto = new global::System.Data.DataColumn("idConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidConcepto);
                this.columnDescripcionConcepto = new global::System.Data.DataColumn("DescripcionConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConcepto);
                this.columnidCuenta = new global::System.Data.DataColumn("idCuenta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidCuenta);
                this.columnDescripcionCuenta = new global::System.Data.DataColumn("DescripcionCuenta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionCuenta);
                this.columnidPeriodo = new global::System.Data.DataColumn("idPeriodo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidPeriodo);
                this.columnValor = new global::System.Data.DataColumn("Valor", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnValor);
                this.columnFlagImprime = new global::System.Data.DataColumn("FlagImprime", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFlagImprime);
                this.columnTipo = new global::System.Data.DataColumn("Tipo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipo);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoRow NewtblEstadoResultadoRow() {
                return ((tblEstadoResultadoRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tblEstadoResultadoRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(tblEstadoResultadoRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblEstadoResultadoRowChanged != null)) {
                    this.tblEstadoResultadoRowChanged(this, new tblEstadoResultadoRowChangeEvent(((tblEstadoResultadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblEstadoResultadoRowChanging != null)) {
                    this.tblEstadoResultadoRowChanging(this, new tblEstadoResultadoRowChangeEvent(((tblEstadoResultadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblEstadoResultadoRowDeleted != null)) {
                    this.tblEstadoResultadoRowDeleted(this, new tblEstadoResultadoRowChangeEvent(((tblEstadoResultadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblEstadoResultadoRowDeleting != null)) {
                    this.tblEstadoResultadoRowDeleting(this, new tblEstadoResultadoRowChangeEvent(((tblEstadoResultadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovetblEstadoResultadoRow(tblEstadoResultadoRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtsEstadoResultado ds = new dtsEstadoResultado();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tblEstadoResultadoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class tblEstadoResultadoRow : global::System.Data.DataRow {
            
            private tblEstadoResultadoDataTable tabletblEstadoResultado;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoResultadoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblEstadoResultado = ((tblEstadoResultadoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int idConsolidado {
                get {
                    try {
                        return ((int)(this[this.tabletblEstadoResultado.idConsolidadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idConsolidado\' de la tabla \'tblEstadoResultado\' es DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.idConsolidadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConsolidado {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.DescripcionConsolidadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConsolidado\' de la tabla \'tblEstadoResultado\' " +
                                "es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.DescripcionConsolidadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idCompania {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.idCompaniaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idCompania\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.idCompaniaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionCompania {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.DescripcionCompaniaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionCompania\' de la tabla \'tblEstadoResultado\' es " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.DescripcionCompaniaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.idGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idGrupo\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.idGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.DescripcionGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionGrupo\' de la tabla \'tblEstadoResultado\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.DescripcionGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.idConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idConcepto\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.idConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.DescripcionConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConcepto\' de la tabla \'tblEstadoResultado\' es " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.DescripcionConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idCuenta {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.idCuentaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idCuenta\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.idCuentaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionCuenta {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.DescripcionCuentaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionCuenta\' de la tabla \'tblEstadoResultado\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.DescripcionCuentaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idPeriodo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.idPeriodoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idPeriodo\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.idPeriodoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Valor {
                get {
                    try {
                        return ((decimal)(this[this.tabletblEstadoResultado.ValorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'Valor\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.ValorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int FlagImprime {
                get {
                    try {
                        return ((int)(this[this.tabletblEstadoResultado.FlagImprimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'FlagImprime\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.FlagImprimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Tipo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultado.TipoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'Tipo\' de la tabla \'tblEstadoResultado\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultado.TipoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidConsolidadoNull() {
                return this.IsNull(this.tabletblEstadoResultado.idConsolidadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidConsolidadoNull() {
                this[this.tabletblEstadoResultado.idConsolidadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConsolidadoNull() {
                return this.IsNull(this.tabletblEstadoResultado.DescripcionConsolidadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConsolidadoNull() {
                this[this.tabletblEstadoResultado.DescripcionConsolidadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidCompaniaNull() {
                return this.IsNull(this.tabletblEstadoResultado.idCompaniaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidCompaniaNull() {
                this[this.tabletblEstadoResultado.idCompaniaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionCompaniaNull() {
                return this.IsNull(this.tabletblEstadoResultado.DescripcionCompaniaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionCompaniaNull() {
                this[this.tabletblEstadoResultado.DescripcionCompaniaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidGrupoNull() {
                return this.IsNull(this.tabletblEstadoResultado.idGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidGrupoNull() {
                this[this.tabletblEstadoResultado.idGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionGrupoNull() {
                return this.IsNull(this.tabletblEstadoResultado.DescripcionGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionGrupoNull() {
                this[this.tabletblEstadoResultado.DescripcionGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidConceptoNull() {
                return this.IsNull(this.tabletblEstadoResultado.idConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidConceptoNull() {
                this[this.tabletblEstadoResultado.idConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConceptoNull() {
                return this.IsNull(this.tabletblEstadoResultado.DescripcionConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConceptoNull() {
                this[this.tabletblEstadoResultado.DescripcionConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidCuentaNull() {
                return this.IsNull(this.tabletblEstadoResultado.idCuentaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidCuentaNull() {
                this[this.tabletblEstadoResultado.idCuentaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionCuentaNull() {
                return this.IsNull(this.tabletblEstadoResultado.DescripcionCuentaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionCuentaNull() {
                this[this.tabletblEstadoResultado.DescripcionCuentaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidPeriodoNull() {
                return this.IsNull(this.tabletblEstadoResultado.idPeriodoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidPeriodoNull() {
                this[this.tabletblEstadoResultado.idPeriodoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsValorNull() {
                return this.IsNull(this.tabletblEstadoResultado.ValorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetValorNull() {
                this[this.tabletblEstadoResultado.ValorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFlagImprimeNull() {
                return this.IsNull(this.tabletblEstadoResultado.FlagImprimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFlagImprimeNull() {
                this[this.tabletblEstadoResultado.FlagImprimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipoNull() {
                return this.IsNull(this.tabletblEstadoResultado.TipoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipoNull() {
                this[this.tabletblEstadoResultado.TipoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class tblEstadoResultadoRowChangeEvent : global::System.EventArgs {
            
            private tblEstadoResultadoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoRowChangeEvent(tblEstadoResultadoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591