//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5420
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewConsolidado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewConsolidado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppNewConsolidado {
            get {
                object obj = ResourceManager.GetObject("AppNewConsolidado", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icafal {
            get {
                object obj = ResourceManager.GetObject("icafal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] importar {
            get {
                object obj = ResourceManager.GetObject("importar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_128_Consolidado01 {
            get {
                object obj = ResourceManager.GetObject("rsc_128_Consolidado01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Agrupador {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Agrupador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Bueno {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Bueno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Buscar {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Buscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_ClearLeft {
            get {
                object obj = ResourceManager.GetObject("rsc_16_ClearLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Consolidado {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Consolidado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Consolidado_pkg {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Consolidado_pkg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_ConsolidadoBook {
            get {
                object obj = ResourceManager.GetObject("rsc_16_ConsolidadoBook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Consolidados {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Consolidados", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Download {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Empresa {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Empresa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Lock {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Malo {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Malo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_refresh {
            get {
                object obj = ResourceManager.GetObject("rsc_16_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_16_Root {
            get {
                object obj = ResourceManager.GetObject("rsc_16_Root", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_AjustesAutomaticos {
            get {
                object obj = ResourceManager.GetObject("rsc_24_AjustesAutomaticos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Borrar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Borrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Buscar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Buscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Cancelar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Cancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Carpetanueva {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Carpetanueva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_ConsolidadoBook {
            get {
                object obj = ResourceManager.GetObject("rsc_24_ConsolidadoBook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_ConsolidadoBook1 {
            get {
                object obj = ResourceManager.GetObject("rsc_24_ConsolidadoBook1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_ConsolidadoNuevo {
            get {
                object obj = ResourceManager.GetObject("rsc_24_ConsolidadoNuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_copiar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_copiar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Cortar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Cortar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Editar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Editar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_EmpresaNueva {
            get {
                object obj = ResourceManager.GetObject("rsc_24_EmpresaNueva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Grabar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Grabar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Impresora {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Impresora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_MoverAbajo {
            get {
                object obj = ResourceManager.GetObject("rsc_24_MoverAbajo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_MoverArriba {
            get {
                object obj = ResourceManager.GetObject("rsc_24_MoverArriba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Nuevo {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Nuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Pegar {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Pegar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_Preferencias {
            get {
                object obj = ResourceManager.GetObject("rsc_24_Preferencias", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_refresh {
            get {
                object obj = ResourceManager.GetObject("rsc_24_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_SalirApp {
            get {
                object obj = ResourceManager.GetObject("rsc_24_SalirApp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_SalirForm {
            get {
                object obj = ResourceManager.GetObject("rsc_24_SalirForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsc_24_update {
            get {
                object obj = ResourceManager.GetObject("rsc_24_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon zen_icon {
            get {
                object obj = ResourceManager.GetObject("zen_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
