//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5420
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewConsolidado.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState usrAppWindowEstado {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["usrAppWindowEstado"]));
            }
            set {
                this["usrAppWindowEstado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int usrAppAncho {
            get {
                return ((int)(this["usrAppAncho"]));
            }
            set {
                this["usrAppAncho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int usrAppAlto {
            get {
                return ((int)(this["usrAppAlto"]));
            }
            set {
                this["usrAppAlto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int usrAppIzquierda {
            get {
                return ((int)(this["usrAppIzquierda"]));
            }
            set {
                this["usrAppIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int usrAppTop {
            get {
                return ((int)(this["usrAppTop"]));
            }
            set {
                this["usrAppTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int myLog4NetDestino {
            get {
                return ((int)(this["myLog4NetDestino"]));
            }
            set {
                this["myLog4NetDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usrRutaArchivos {
            get {
                return ((string)(this["usrRutaArchivos"]));
            }
            set {
                this["usrRutaArchivos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImageAndText")]
        public global::System.Windows.Forms.ToolStripItemDisplayStyle usrMuestraToolbar {
            get {
                return ((global::System.Windows.Forms.ToolStripItemDisplayStyle)(this["usrMuestraToolbar"]));
            }
            set {
                this["usrMuestraToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int usrDiseñoToolbar {
            get {
                return ((int)(this["usrDiseñoToolbar"]));
            }
            set {
                this["usrDiseñoToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int myLog4NetNivel {
            get {
                return ((int)(this["myLog4NetNivel"]));
            }
            set {
                this["myLog4NetNivel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usrUsuarioWindows {
            get {
                return ((string)(this["usrUsuarioWindows"]));
            }
            set {
                this["usrUsuarioWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int usrDiseñoBotones {
            get {
                return ((int)(this["usrDiseñoBotones"]));
            }
            set {
                this["usrDiseñoBotones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usrMuestraCamposOcultos {
            get {
                return ((bool)(this["usrMuestraCamposOcultos"]));
            }
            set {
                this["usrMuestraCamposOcultos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usrMuestraColumnasOcultas {
            get {
                return ((bool)(this["usrMuestraColumnasOcultas"]));
            }
            set {
                this["usrMuestraColumnasOcultas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usrPreguntarAlSalir {
            get {
                return ((bool)(this["usrPreguntarAlSalir"]));
            }
            set {
                this["usrPreguntarAlSalir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REAL,NOLOB,IFRS")]
        public string usrLibrosReporte {
            get {
                return ((string)(this["usrLibrosReporte"]));
            }
            set {
                this["usrLibrosReporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usrPreguntaEliminar {
            get {
                return ((bool)(this["usrPreguntaEliminar"]));
            }
            set {
                this["usrPreguntaEliminar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usrPreguntaFormulariosSalir {
            get {
                return ((bool)(this["usrPreguntaFormulariosSalir"]));
            }
            set {
                this["usrPreguntaFormulariosSalir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5, 5")]
        public global::System.Drawing.Point frmMantenedorConsolidado {
            get {
                return ((global::System.Drawing.Point)(this["frmMantenedorConsolidado"]));
            }
            set {
                this["frmMantenedorConsolidado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmMantenedorConsolidadoEstado {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmMantenedorConsolidadoEstado"]));
            }
            set {
                this["frmMantenedorConsolidadoEstado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usrRecorarPosicionFormularios {
            get {
                return ((bool)(this["usrRecorarPosicionFormularios"]));
            }
            set {
                this["usrRecorarPosicionFormularios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5, 5")]
        public global::System.Drawing.Point frmIngresoAjustesManuales {
            get {
                return ((global::System.Drawing.Point)(this["frmIngresoAjustesManuales"]));
            }
            set {
                this["frmIngresoAjustesManuales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmIngresoAjustesManualesEstado {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmIngresoAjustesManualesEstado"]));
            }
            set {
                this["frmIngresoAjustesManualesEstado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("523")]
        public int frmMantenedorConsolidadoAlto {
            get {
                return ((int)(this["frmMantenedorConsolidadoAlto"]));
            }
            set {
                this["frmMantenedorConsolidadoAlto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("782")]
        public int frmMantenedorConsolidadoAncho {
            get {
                return ((int)(this["frmMantenedorConsolidadoAncho"]));
            }
            set {
                this["frmMantenedorConsolidadoAncho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int usrUsuarioTipo {
            get {
                return ((int)(this["usrUsuarioTipo"]));
            }
            set {
                this["usrUsuarioTipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usrRutaArchivosLog {
            get {
                return ((string)(this["usrRutaArchivosLog"]));
            }
            set {
                this["usrRutaArchivosLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usrRutaArchivosPaso {
            get {
                return ((string)(this["usrRutaArchivosPaso"]));
            }
            set {
                this["usrRutaArchivosPaso"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strConnSource {
            get {
                return ((string)(this["strConnSource"]));
            }
            set {
                this["strConnSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strConnCatalog {
            get {
                return ((string)(this["strConnCatalog"]));
            }
            set {
                this["strConnCatalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strConnUser {
            get {
                return ((string)(this["strConnUser"]));
            }
            set {
                this["strConnUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strConnPassword {
            get {
                return ((string)(this["strConnPassword"]));
            }
            set {
                this["strConnPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolidación de Empresas Relacionadas")]
        public string appTituloAplicacion {
            get {
                return ((string)(this["appTituloAplicacion"]));
            }
            set {
                this["appTituloAplicacion"] = value;
            }
        }
    }
}
