//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5420
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace NewConsolidado.Vistas.Reportes.ESFSuperintendencia {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtsEstadoSituacionSuper")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtsEstadoSituacionSuper : global::System.Data.DataSet {
        
        private tblEstadoSituacionSuperDataTable tabletblEstadoSituacionSuper;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtsEstadoSituacionSuper() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dtsEstadoSituacionSuper(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblEstadoSituacionSuper"] != null)) {
                    base.Tables.Add(new tblEstadoSituacionSuperDataTable(ds.Tables["tblEstadoSituacionSuper"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblEstadoSituacionSuperDataTable tblEstadoSituacionSuper {
            get {
                return this.tabletblEstadoSituacionSuper;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dtsEstadoSituacionSuper cln = ((dtsEstadoSituacionSuper)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tblEstadoSituacionSuper"] != null)) {
                    base.Tables.Add(new tblEstadoSituacionSuperDataTable(ds.Tables["tblEstadoSituacionSuper"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabletblEstadoSituacionSuper = ((tblEstadoSituacionSuperDataTable)(base.Tables["tblEstadoSituacionSuper"]));
            if ((initTable == true)) {
                if ((this.tabletblEstadoSituacionSuper != null)) {
                    this.tabletblEstadoSituacionSuper.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dtsEstadoSituacionSuper";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtsEstadoSituacionSuper.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletblEstadoSituacionSuper = new tblEstadoSituacionSuperDataTable();
            base.Tables.Add(this.tabletblEstadoSituacionSuper);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializetblEstadoSituacionSuper() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtsEstadoSituacionSuper ds = new dtsEstadoSituacionSuper();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void tblEstadoSituacionSuperRowChangeEventHandler(object sender, tblEstadoSituacionSuperRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tblEstadoSituacionSuperDataTable : global::System.Data.TypedTableBase<tblEstadoSituacionSuperRow> {
            
            private global::System.Data.DataColumn columnIdPatrimonio;
            
            private global::System.Data.DataColumn columnidGrupo;
            
            private global::System.Data.DataColumn columnidConcepto;
            
            private global::System.Data.DataColumn columnValor1;
            
            private global::System.Data.DataColumn columnValor2;
            
            private global::System.Data.DataColumn columnDescripcionPatrimonio;
            
            private global::System.Data.DataColumn columnDescripcionGrupo;
            
            private global::System.Data.DataColumn columnDescripcionConcepto;
            
            private global::System.Data.DataColumn columnidPeriodo1;
            
            private global::System.Data.DataColumn columnidPeriodo2;
            
            private global::System.Data.DataColumn columnDescripcionConsolidado;
            
            private global::System.Data.DataColumn columnFlagSumaESF;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionSuperDataTable() {
                this.TableName = "tblEstadoSituacionSuper";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoSituacionSuperDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected tblEstadoSituacionSuperDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdPatrimonioColumn {
                get {
                    return this.columnIdPatrimonio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idGrupoColumn {
                get {
                    return this.columnidGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idConceptoColumn {
                get {
                    return this.columnidConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Valor1Column {
                get {
                    return this.columnValor1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Valor2Column {
                get {
                    return this.columnValor2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionPatrimonioColumn {
                get {
                    return this.columnDescripcionPatrimonio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionGrupoColumn {
                get {
                    return this.columnDescripcionGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConceptoColumn {
                get {
                    return this.columnDescripcionConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idPeriodo1Column {
                get {
                    return this.columnidPeriodo1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idPeriodo2Column {
                get {
                    return this.columnidPeriodo2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConsolidadoColumn {
                get {
                    return this.columnDescripcionConsolidado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FlagSumaESFColumn {
                get {
                    return this.columnFlagSumaESF;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionSuperRow this[int index] {
                get {
                    return ((tblEstadoSituacionSuperRow)(this.Rows[index]));
                }
            }
            
            public event tblEstadoSituacionSuperRowChangeEventHandler tblEstadoSituacionSuperRowChanging;
            
            public event tblEstadoSituacionSuperRowChangeEventHandler tblEstadoSituacionSuperRowChanged;
            
            public event tblEstadoSituacionSuperRowChangeEventHandler tblEstadoSituacionSuperRowDeleting;
            
            public event tblEstadoSituacionSuperRowChangeEventHandler tblEstadoSituacionSuperRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddtblEstadoSituacionSuperRow(tblEstadoSituacionSuperRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionSuperRow AddtblEstadoSituacionSuperRow(string IdPatrimonio, string idGrupo, string idConcepto, decimal Valor1, decimal Valor2, string DescripcionPatrimonio, string DescripcionGrupo, string DescripcionConcepto, string idPeriodo1, string idPeriodo2, string DescripcionConsolidado, string FlagSumaESF) {
                tblEstadoSituacionSuperRow rowtblEstadoSituacionSuperRow = ((tblEstadoSituacionSuperRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IdPatrimonio,
                        idGrupo,
                        idConcepto,
                        Valor1,
                        Valor2,
                        DescripcionPatrimonio,
                        DescripcionGrupo,
                        DescripcionConcepto,
                        idPeriodo1,
                        idPeriodo2,
                        DescripcionConsolidado,
                        FlagSumaESF};
                rowtblEstadoSituacionSuperRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtblEstadoSituacionSuperRow);
                return rowtblEstadoSituacionSuperRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                tblEstadoSituacionSuperDataTable cln = ((tblEstadoSituacionSuperDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tblEstadoSituacionSuperDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnIdPatrimonio = base.Columns["IdPatrimonio"];
                this.columnidGrupo = base.Columns["idGrupo"];
                this.columnidConcepto = base.Columns["idConcepto"];
                this.columnValor1 = base.Columns["Valor1"];
                this.columnValor2 = base.Columns["Valor2"];
                this.columnDescripcionPatrimonio = base.Columns["DescripcionPatrimonio"];
                this.columnDescripcionGrupo = base.Columns["DescripcionGrupo"];
                this.columnDescripcionConcepto = base.Columns["DescripcionConcepto"];
                this.columnidPeriodo1 = base.Columns["idPeriodo1"];
                this.columnidPeriodo2 = base.Columns["idPeriodo2"];
                this.columnDescripcionConsolidado = base.Columns["DescripcionConsolidado"];
                this.columnFlagSumaESF = base.Columns["FlagSumaESF"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnIdPatrimonio = new global::System.Data.DataColumn("IdPatrimonio", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdPatrimonio);
                this.columnidGrupo = new global::System.Data.DataColumn("idGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidGrupo);
                this.columnidConcepto = new global::System.Data.DataColumn("idConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidConcepto);
                this.columnValor1 = new global::System.Data.DataColumn("Valor1", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnValor1);
                this.columnValor2 = new global::System.Data.DataColumn("Valor2", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnValor2);
                this.columnDescripcionPatrimonio = new global::System.Data.DataColumn("DescripcionPatrimonio", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionPatrimonio);
                this.columnDescripcionGrupo = new global::System.Data.DataColumn("DescripcionGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionGrupo);
                this.columnDescripcionConcepto = new global::System.Data.DataColumn("DescripcionConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConcepto);
                this.columnidPeriodo1 = new global::System.Data.DataColumn("idPeriodo1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidPeriodo1);
                this.columnidPeriodo2 = new global::System.Data.DataColumn("idPeriodo2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidPeriodo2);
                this.columnDescripcionConsolidado = new global::System.Data.DataColumn("DescripcionConsolidado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConsolidado);
                this.columnFlagSumaESF = new global::System.Data.DataColumn("FlagSumaESF", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFlagSumaESF);
                this.columnValor1.Caption = "Valor";
                this.columnValor2.Caption = "Valor";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionSuperRow NewtblEstadoSituacionSuperRow() {
                return ((tblEstadoSituacionSuperRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tblEstadoSituacionSuperRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(tblEstadoSituacionSuperRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblEstadoSituacionSuperRowChanged != null)) {
                    this.tblEstadoSituacionSuperRowChanged(this, new tblEstadoSituacionSuperRowChangeEvent(((tblEstadoSituacionSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblEstadoSituacionSuperRowChanging != null)) {
                    this.tblEstadoSituacionSuperRowChanging(this, new tblEstadoSituacionSuperRowChangeEvent(((tblEstadoSituacionSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblEstadoSituacionSuperRowDeleted != null)) {
                    this.tblEstadoSituacionSuperRowDeleted(this, new tblEstadoSituacionSuperRowChangeEvent(((tblEstadoSituacionSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblEstadoSituacionSuperRowDeleting != null)) {
                    this.tblEstadoSituacionSuperRowDeleting(this, new tblEstadoSituacionSuperRowChangeEvent(((tblEstadoSituacionSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovetblEstadoSituacionSuperRow(tblEstadoSituacionSuperRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtsEstadoSituacionSuper ds = new dtsEstadoSituacionSuper();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tblEstadoSituacionSuperDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class tblEstadoSituacionSuperRow : global::System.Data.DataRow {
            
            private tblEstadoSituacionSuperDataTable tabletblEstadoSituacionSuper;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoSituacionSuperRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblEstadoSituacionSuper = ((tblEstadoSituacionSuperDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string IdPatrimonio {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.IdPatrimonioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IdPatrimonio\' de la tabla \'tblEstadoSituacionSuper\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.IdPatrimonioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.idGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idGrupo\' de la tabla \'tblEstadoSituacionSuper\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.idGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.idConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idConcepto\' de la tabla \'tblEstadoSituacionSuper\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.idConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Valor1 {
                get {
                    try {
                        return ((decimal)(this[this.tabletblEstadoSituacionSuper.Valor1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'Valor1\' de la tabla \'tblEstadoSituacionSuper\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.Valor1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Valor2 {
                get {
                    try {
                        return ((decimal)(this[this.tabletblEstadoSituacionSuper.Valor2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'Valor2\' de la tabla \'tblEstadoSituacionSuper\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.Valor2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionPatrimonio {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.DescripcionPatrimonioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionPatrimonio\' de la tabla \'tblEstadoSituacionSup" +
                                "er\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.DescripcionPatrimonioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.DescripcionGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionGrupo\' de la tabla \'tblEstadoSituacionSuper\' e" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.DescripcionGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.DescripcionConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConcepto\' de la tabla \'tblEstadoSituacionSuper" +
                                "\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.DescripcionConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idPeriodo1 {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.idPeriodo1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idPeriodo1\' de la tabla \'tblEstadoSituacionSuper\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.idPeriodo1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idPeriodo2 {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.idPeriodo2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idPeriodo2\' de la tabla \'tblEstadoSituacionSuper\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.idPeriodo2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConsolidado {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.DescripcionConsolidadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConsolidado\' de la tabla \'tblEstadoSituacionSu" +
                                "per\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.DescripcionConsolidadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FlagSumaESF {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoSituacionSuper.FlagSumaESFColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'FlagSumaESF\' de la tabla \'tblEstadoSituacionSuper\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoSituacionSuper.FlagSumaESFColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIdPatrimonioNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.IdPatrimonioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIdPatrimonioNull() {
                this[this.tabletblEstadoSituacionSuper.IdPatrimonioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidGrupoNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.idGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidGrupoNull() {
                this[this.tabletblEstadoSituacionSuper.idGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidConceptoNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.idConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidConceptoNull() {
                this[this.tabletblEstadoSituacionSuper.idConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsValor1Null() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.Valor1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetValor1Null() {
                this[this.tabletblEstadoSituacionSuper.Valor1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsValor2Null() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.Valor2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetValor2Null() {
                this[this.tabletblEstadoSituacionSuper.Valor2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionPatrimonioNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.DescripcionPatrimonioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionPatrimonioNull() {
                this[this.tabletblEstadoSituacionSuper.DescripcionPatrimonioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionGrupoNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.DescripcionGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionGrupoNull() {
                this[this.tabletblEstadoSituacionSuper.DescripcionGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConceptoNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.DescripcionConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConceptoNull() {
                this[this.tabletblEstadoSituacionSuper.DescripcionConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidPeriodo1Null() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.idPeriodo1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidPeriodo1Null() {
                this[this.tabletblEstadoSituacionSuper.idPeriodo1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidPeriodo2Null() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.idPeriodo2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidPeriodo2Null() {
                this[this.tabletblEstadoSituacionSuper.idPeriodo2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConsolidadoNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.DescripcionConsolidadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConsolidadoNull() {
                this[this.tabletblEstadoSituacionSuper.DescripcionConsolidadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFlagSumaESFNull() {
                return this.IsNull(this.tabletblEstadoSituacionSuper.FlagSumaESFColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFlagSumaESFNull() {
                this[this.tabletblEstadoSituacionSuper.FlagSumaESFColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class tblEstadoSituacionSuperRowChangeEvent : global::System.EventArgs {
            
            private tblEstadoSituacionSuperRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionSuperRowChangeEvent(tblEstadoSituacionSuperRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoSituacionSuperRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591