//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8762
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace NewConsolidado.Vistas.Reportes.ERFSuperintendencia {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtsEstadoResultadoSuper")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtsEstadoResultadoSuper : global::System.Data.DataSet {
        
        private tblEstadoResultadoSuperDataTable tabletblEstadoResultadoSuper;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtsEstadoResultadoSuper() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dtsEstadoResultadoSuper(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblEstadoResultadoSuper"] != null)) {
                    base.Tables.Add(new tblEstadoResultadoSuperDataTable(ds.Tables["tblEstadoResultadoSuper"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblEstadoResultadoSuperDataTable tblEstadoResultadoSuper {
            get {
                return this.tabletblEstadoResultadoSuper;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dtsEstadoResultadoSuper cln = ((dtsEstadoResultadoSuper)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tblEstadoResultadoSuper"] != null)) {
                    base.Tables.Add(new tblEstadoResultadoSuperDataTable(ds.Tables["tblEstadoResultadoSuper"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabletblEstadoResultadoSuper = ((tblEstadoResultadoSuperDataTable)(base.Tables["tblEstadoResultadoSuper"]));
            if ((initTable == true)) {
                if ((this.tabletblEstadoResultadoSuper != null)) {
                    this.tabletblEstadoResultadoSuper.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dtsEstadoResultadoSuper";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtsEstadoResultadoSuper.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletblEstadoResultadoSuper = new tblEstadoResultadoSuperDataTable();
            base.Tables.Add(this.tabletblEstadoResultadoSuper);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializetblEstadoResultadoSuper() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtsEstadoResultadoSuper ds = new dtsEstadoResultadoSuper();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void tblEstadoResultadoSuperRowChangeEventHandler(object sender, tblEstadoResultadoSuperRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tblEstadoResultadoSuperDataTable : global::System.Data.TypedTableBase<tblEstadoResultadoSuperRow> {
            
            private global::System.Data.DataColumn columnidGrupo;
            
            private global::System.Data.DataColumn columnidConcepto;
            
            private global::System.Data.DataColumn columnValor1;
            
            private global::System.Data.DataColumn columnValor2;
            
            private global::System.Data.DataColumn columnDescripcionGrupo;
            
            private global::System.Data.DataColumn columnDescripcionConcepto;
            
            private global::System.Data.DataColumn columnidPeriodo1;
            
            private global::System.Data.DataColumn columnidPeriodo2;
            
            private global::System.Data.DataColumn columnDescripcionConsolidado;
            
            private global::System.Data.DataColumn columnTipoLinea;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoSuperDataTable() {
                this.TableName = "tblEstadoResultadoSuper";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoResultadoSuperDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected tblEstadoResultadoSuperDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idGrupoColumn {
                get {
                    return this.columnidGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idConceptoColumn {
                get {
                    return this.columnidConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Valor1Column {
                get {
                    return this.columnValor1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Valor2Column {
                get {
                    return this.columnValor2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionGrupoColumn {
                get {
                    return this.columnDescripcionGrupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConceptoColumn {
                get {
                    return this.columnDescripcionConcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idPeriodo1Column {
                get {
                    return this.columnidPeriodo1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idPeriodo2Column {
                get {
                    return this.columnidPeriodo2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescripcionConsolidadoColumn {
                get {
                    return this.columnDescripcionConsolidado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipoLineaColumn {
                get {
                    return this.columnTipoLinea;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoSuperRow this[int index] {
                get {
                    return ((tblEstadoResultadoSuperRow)(this.Rows[index]));
                }
            }
            
            public event tblEstadoResultadoSuperRowChangeEventHandler tblEstadoResultadoSuperRowChanging;
            
            public event tblEstadoResultadoSuperRowChangeEventHandler tblEstadoResultadoSuperRowChanged;
            
            public event tblEstadoResultadoSuperRowChangeEventHandler tblEstadoResultadoSuperRowDeleting;
            
            public event tblEstadoResultadoSuperRowChangeEventHandler tblEstadoResultadoSuperRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddtblEstadoResultadoSuperRow(tblEstadoResultadoSuperRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoSuperRow AddtblEstadoResultadoSuperRow(string idGrupo, string idConcepto, decimal Valor1, decimal Valor2, string DescripcionGrupo, string DescripcionConcepto, string idPeriodo1, string idPeriodo2, string DescripcionConsolidado, string TipoLinea) {
                tblEstadoResultadoSuperRow rowtblEstadoResultadoSuperRow = ((tblEstadoResultadoSuperRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        idGrupo,
                        idConcepto,
                        Valor1,
                        Valor2,
                        DescripcionGrupo,
                        DescripcionConcepto,
                        idPeriodo1,
                        idPeriodo2,
                        DescripcionConsolidado,
                        TipoLinea};
                rowtblEstadoResultadoSuperRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtblEstadoResultadoSuperRow);
                return rowtblEstadoResultadoSuperRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                tblEstadoResultadoSuperDataTable cln = ((tblEstadoResultadoSuperDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tblEstadoResultadoSuperDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnidGrupo = base.Columns["idGrupo"];
                this.columnidConcepto = base.Columns["idConcepto"];
                this.columnValor1 = base.Columns["Valor1"];
                this.columnValor2 = base.Columns["Valor2"];
                this.columnDescripcionGrupo = base.Columns["DescripcionGrupo"];
                this.columnDescripcionConcepto = base.Columns["DescripcionConcepto"];
                this.columnidPeriodo1 = base.Columns["idPeriodo1"];
                this.columnidPeriodo2 = base.Columns["idPeriodo2"];
                this.columnDescripcionConsolidado = base.Columns["DescripcionConsolidado"];
                this.columnTipoLinea = base.Columns["TipoLinea"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnidGrupo = new global::System.Data.DataColumn("idGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidGrupo);
                this.columnidConcepto = new global::System.Data.DataColumn("idConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidConcepto);
                this.columnValor1 = new global::System.Data.DataColumn("Valor1", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnValor1);
                this.columnValor2 = new global::System.Data.DataColumn("Valor2", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnValor2);
                this.columnDescripcionGrupo = new global::System.Data.DataColumn("DescripcionGrupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionGrupo);
                this.columnDescripcionConcepto = new global::System.Data.DataColumn("DescripcionConcepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConcepto);
                this.columnidPeriodo1 = new global::System.Data.DataColumn("idPeriodo1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidPeriodo1);
                this.columnidPeriodo2 = new global::System.Data.DataColumn("idPeriodo2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidPeriodo2);
                this.columnDescripcionConsolidado = new global::System.Data.DataColumn("DescripcionConsolidado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcionConsolidado);
                this.columnTipoLinea = new global::System.Data.DataColumn("TipoLinea", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipoLinea);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoSuperRow NewtblEstadoResultadoSuperRow() {
                return ((tblEstadoResultadoSuperRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tblEstadoResultadoSuperRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(tblEstadoResultadoSuperRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblEstadoResultadoSuperRowChanged != null)) {
                    this.tblEstadoResultadoSuperRowChanged(this, new tblEstadoResultadoSuperRowChangeEvent(((tblEstadoResultadoSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblEstadoResultadoSuperRowChanging != null)) {
                    this.tblEstadoResultadoSuperRowChanging(this, new tblEstadoResultadoSuperRowChangeEvent(((tblEstadoResultadoSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblEstadoResultadoSuperRowDeleted != null)) {
                    this.tblEstadoResultadoSuperRowDeleted(this, new tblEstadoResultadoSuperRowChangeEvent(((tblEstadoResultadoSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblEstadoResultadoSuperRowDeleting != null)) {
                    this.tblEstadoResultadoSuperRowDeleting(this, new tblEstadoResultadoSuperRowChangeEvent(((tblEstadoResultadoSuperRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovetblEstadoResultadoSuperRow(tblEstadoResultadoSuperRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtsEstadoResultadoSuper ds = new dtsEstadoResultadoSuper();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tblEstadoResultadoSuperDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class tblEstadoResultadoSuperRow : global::System.Data.DataRow {
            
            private tblEstadoResultadoSuperDataTable tabletblEstadoResultadoSuper;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblEstadoResultadoSuperRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblEstadoResultadoSuper = ((tblEstadoResultadoSuperDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.idGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idGrupo\' de la tabla \'tblEstadoResultadoSuper\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.idGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.idConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idConcepto\' de la tabla \'tblEstadoResultadoSuper\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.idConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Valor1 {
                get {
                    try {
                        return ((decimal)(this[this.tabletblEstadoResultadoSuper.Valor1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'Valor1\' de la tabla \'tblEstadoResultadoSuper\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.Valor1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Valor2 {
                get {
                    try {
                        return ((decimal)(this[this.tabletblEstadoResultadoSuper.Valor2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'Valor2\' de la tabla \'tblEstadoResultadoSuper\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.Valor2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionGrupo {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.DescripcionGrupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionGrupo\' de la tabla \'tblEstadoResultadoSuper\' e" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.DescripcionGrupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConcepto {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.DescripcionConceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConcepto\' de la tabla \'tblEstadoResultadoSuper" +
                                "\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.DescripcionConceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idPeriodo1 {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.idPeriodo1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idPeriodo1\' de la tabla \'tblEstadoResultadoSuper\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.idPeriodo1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string idPeriodo2 {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.idPeriodo2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'idPeriodo2\' de la tabla \'tblEstadoResultadoSuper\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.idPeriodo2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DescripcionConsolidado {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.DescripcionConsolidadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DescripcionConsolidado\' de la tabla \'tblEstadoResultadoSu" +
                                "per\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.DescripcionConsolidadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TipoLinea {
                get {
                    try {
                        return ((string)(this[this.tabletblEstadoResultadoSuper.TipoLineaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TipoLinea\' de la tabla \'tblEstadoResultadoSuper\' es DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabletblEstadoResultadoSuper.TipoLineaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidGrupoNull() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.idGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidGrupoNull() {
                this[this.tabletblEstadoResultadoSuper.idGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidConceptoNull() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.idConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidConceptoNull() {
                this[this.tabletblEstadoResultadoSuper.idConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsValor1Null() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.Valor1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetValor1Null() {
                this[this.tabletblEstadoResultadoSuper.Valor1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsValor2Null() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.Valor2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetValor2Null() {
                this[this.tabletblEstadoResultadoSuper.Valor2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionGrupoNull() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.DescripcionGrupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionGrupoNull() {
                this[this.tabletblEstadoResultadoSuper.DescripcionGrupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConceptoNull() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.DescripcionConceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConceptoNull() {
                this[this.tabletblEstadoResultadoSuper.DescripcionConceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidPeriodo1Null() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.idPeriodo1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidPeriodo1Null() {
                this[this.tabletblEstadoResultadoSuper.idPeriodo1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidPeriodo2Null() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.idPeriodo2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidPeriodo2Null() {
                this[this.tabletblEstadoResultadoSuper.idPeriodo2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescripcionConsolidadoNull() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.DescripcionConsolidadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescripcionConsolidadoNull() {
                this[this.tabletblEstadoResultadoSuper.DescripcionConsolidadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipoLineaNull() {
                return this.IsNull(this.tabletblEstadoResultadoSuper.TipoLineaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipoLineaNull() {
                this[this.tabletblEstadoResultadoSuper.TipoLineaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class tblEstadoResultadoSuperRowChangeEvent : global::System.EventArgs {
            
            private tblEstadoResultadoSuperRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoSuperRowChangeEvent(tblEstadoResultadoSuperRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblEstadoResultadoSuperRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591